### PR TITLE
follow plugin naming convention

### PR DESCRIPTION
**Pull request by calid**
the vim plugin convention seems to be to name the plugin file the same
as the plugin name, so renaming to java_import.vim

### CODE REVIEW

**Comment by TimMikeFox** [comment]
I merged the perl pull request before this one and updated the branch before accepting the merge. I'll attempt the merge later tonight as I did not have a good chance to test things.

**Comment by calid** [comment]
I rebased the branch, should be able to merge without issue now

**Comment by calid** [comment]
Ok, I see... I think I misunderstood... so basically the rename commit got merged along with the perl integration?

I've restored the original state of the `rename-plugin-file` branch.  The empty commit isn't necessary as a notation (I would `rebase -i` and kill it)... github is smart and will reflect this as merged automatically whenever the rename commit makes it to master, regardless of how it gets there

**Comment by calid** [comment]
Oh derp, misunderstood again... that's not an empty commit it's another merge commit, my bad!

But yeah regardless if/when it gets merged to master and pushed github will close this PR

**Pull request merged**
